// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWJbkYTB4WmsHV0FlOC8XJTBhwaj5Gk0c',
    appId: '1:625609010715:web:1600d2945d18c4fc2512be',
    messagingSenderId: '625609010715',
    projectId: 'fruit-hub2',
    authDomain: 'fruit-hub2.firebaseapp.com',
    storageBucket: 'fruit-hub2.firebasestorage.app',
    measurementId: 'G-4LM2MKLJML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP3hLntgUGbD8HFMTdsHwBCKPLBycC23w',
    appId: '1:625609010715:android:fcc35123e35462f22512be',
    messagingSenderId: '625609010715',
    projectId: 'fruit-hub2',
    storageBucket: 'fruit-hub2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHd8gyBslEDeGg-i06cg3aMnkGwa56em0',
    appId: '1:625609010715:ios:5ab60633949117462512be',
    messagingSenderId: '625609010715',
    projectId: 'fruit-hub2',
    storageBucket: 'fruit-hub2.firebasestorage.app',
    androidClientId: '625609010715-tb71eo0pugc1of8ce52uebhksljsnf12.apps.googleusercontent.com',
    iosClientId: '625609010715-uvh9phumidogv00cqnu36u60e1iundj0.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHubDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHd8gyBslEDeGg-i06cg3aMnkGwa56em0',
    appId: '1:625609010715:ios:5ab60633949117462512be',
    messagingSenderId: '625609010715',
    projectId: 'fruit-hub2',
    storageBucket: 'fruit-hub2.firebasestorage.app',
    androidClientId: '625609010715-tb71eo0pugc1of8ce52uebhksljsnf12.apps.googleusercontent.com',
    iosClientId: '625609010715-uvh9phumidogv00cqnu36u60e1iundj0.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHubDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWJbkYTB4WmsHV0FlOC8XJTBhwaj5Gk0c',
    appId: '1:625609010715:web:656e14f415e55ca22512be',
    messagingSenderId: '625609010715',
    projectId: 'fruit-hub2',
    authDomain: 'fruit-hub2.firebaseapp.com',
    storageBucket: 'fruit-hub2.firebasestorage.app',
    measurementId: 'G-TQY8FDPRJ0',
  );
}
